# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Godot Engine Francophone"
alt_title:  "Godot Francophone"
email: "-"
description: >
  Nous sommes la communauté francophone de Godot Engine.
  On partage des tutoriels et des ressource utiles en français.
baseurl: ""
url: "https://www.godot-francophone.org"
twitter_username: "godotenginefr"
github_username:  "Godot-Engine-Francophone"
color_theme:  "#fefefe"
color_text:  "#0e0e0e"
language:  "fr"
tag: godot, godot engine, engine, francais, france, tutoriel, francophone, discord, communauté

# Build settings
markdown: kramdown
permalink: /:title/
pagination:
  enabled: true
  per_page: 12
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Color:
color:
  icon: "#f7fbff"
  tag_color: "#297AC3"
  footer:
    background: "#01365c"
  theme: "#fefefe"
  text: "#0e0e0e"
  link:
    visited: "#020202"
    active: "#020202"
    link: "#020202"
    hover: "#020202"

highlighter: rouge

# Plugins
plugins_dir:
  - jekyll-admin
  - jekyll-paginate-v2

facebook:
  app_id: "00000000"
  admins: "00000000"

social_sites:
  twitter: godotenginefr
  # youtube: Binogure studio
  # youtube_uri: UCICwKQU-TUX24Ocm1Axsbeg
  github:  Godot-Engine-Francophone
  discord: NQVd34V
  # dribbble: jekyll
  # facebook: Binogure
  #flickr: jekyll
  #instagram: jekyll
  #linkedin: jekyll
  #pinterest: jekyll

exclude: [vendor]